# Generated by Django 5.2.5 on 2025-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wall_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.URLField(
                default="https://randomuser.me/api/portraits/lego/2.jpg"
            ),
        ),
    ]
